services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: php-prod
      args:
        PHP_VERSION: "8.3"
    container_name: laravel-app
    environment:
      APP_ENV: production
    env_file: .env.prod

  nginx:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: nginx-prod
    container_name: laravel-nginx
    ports:
      - "${WEB_PORT:-80}:80"
    depends_on:
      - app
