services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: php-dev
      args:
        PHP_VERSION: "8.3"
    container_name: laravel-app
    volumes:
      - ./:/var/www
    environment:
      APP_ENV: local

  nginx:
    image: nginx:1.27-alpine
    container_name: laravel-nginx
    ports:
      - "${WEB_PORT:-8080}:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/public:ro
    depends_on:
      - app

  node:
    image: node:20-alpine
    container_name: laravel-node
    working_dir: /var/www
    command: sh -c "npm ci && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
