<?php

return [
    'default_cooldown_minutes' => 30,

    'definitions' => [
        'site_availability' => [
            'name' => 'Disponibilidad del sitio (hoy)',
            'description' => 'Porcentaje de disponibilidad diaria del sitio.',
            'table' => 'site_daily_kpi',
            'value_column' => 'availability_pct',
            'date_column' => 'kpi_date',
            'timeframe' => 'today',
            'format' => 'percentage_loose',
            'unit' => '%',
            'supports_site_selection' => true,
            'default_operator' => 'below',
            'default_threshold' => 95,
        ],
        'energy_today_kpi' => [
            'name' => 'Energía generada hoy',
            'description' => 'Energía total acumulada del sitio en el día actual.',
            'table' => 'site_daily_kpi',
            'value_column' => 'total_energy_wh',
            'date_column' => 'kpi_date',
            'timeframe' => 'today',
            'format' => 'number',
            'unit' => 'Wh',
            'supports_site_selection' => true,
            'default_operator' => 'below',
            'default_threshold' => 1000,
        ],
        'peak_power_kpi' => [
            'name' => 'Potencia pico del día',
            'description' => 'Valor máximo de potencia registrado durante el día.',
            'table' => 'site_daily_kpi',
            'value_column' => 'peak_power_w',
            'date_column' => 'kpi_date',
            'timeframe' => 'today',
            'format' => 'number',
            'unit' => 'W',
            'supports_site_selection' => true,
            'default_operator' => 'above',
            'default_threshold' => 50000,
        ],
        'load_factor_kpi' => [
            'name' => 'Load factor diario',
            'description' => 'Relación entre energía real generada y máxima posible.',
            'table' => 'site_daily_kpi',
            'value_column' => 'load_factor',
            'date_column' => 'kpi_date',
            'timeframe' => 'today',
            'format' => 'percentage',
            'unit' => '%',
            'supports_site_selection' => true,
            'default_operator' => 'below',
            'default_threshold' => 65,
        ],
        'pf_compliance_kpi' => [
            'name' => 'Cumplimiento factor de potencia',
            'description' => 'Porcentaje de cumplimiento del PF objetivo.',
            'table' => 'site_daily_kpi',
            'value_column' => 'pf_compliance_pct',
            'date_column' => 'kpi_date',
            'timeframe' => 'today',
            'format' => 'percentage',
            'unit' => '%',
            'supports_site_selection' => true,
            'default_operator' => 'below',
            'default_threshold' => 90,
        ],
        'data_freshness_kpi' => [
            'name' => 'Latencia de datos',
            'description' => 'Minutos transcurridos desde la última actualización de datos.',
            'table' => 'site_daily_kpi',
            'value_column' => 'data_freshness_minutes',
            'date_column' => 'kpi_date',
            'timeframe' => 'today',
            'format' => 'number',
            'unit' => 'min',
            'supports_site_selection' => true,
            'default_operator' => 'above',
            'default_threshold' => 30,
        ],
        'active_devices_kpi' => [
            'name' => 'Dispositivos activos (última hora)',
            'description' => 'Conteo de dispositivos que reportaron datos en la última hora.',
            'table' => 'site_hourly_kpi',
            'value_column' => 'active_devices',
            'total_column' => 'total_devices',
            'date_column' => 'hour_start',
            'timeframe' => 'latest_hour',
            'format' => 'number',
            'unit' => 'devices',
            'supports_site_selection' => true,
            'default_operator' => 'below',
            'default_threshold' => 1,
        ],
    ],
];
